### PR TITLE
Fix revenues summed too many times

### PR DESCRIPTION
**Pull request by samulikyytsonen**
This affects only to the results in .txt file - not CBA-excel

### CODE REVIEW

**Review by zptro — DISMISSED** [review]
Nice catch!

**Comment by hsl-petrhaj** [comment]
@samulikyytsonen I am not so familiar with this part, but why is the proposed behavior inconsistent with how cars are counted? Is there some underlying difference?

**Review by hsl-petrhaj — APPROVED** [review]
Now it looks consistent, thank you for the PR. You can squash merge that into olusanya now (as usual).

**Comment by samulikyytsonen** [comment]
Seems that I don't have rights to do the merge. I need to be authorized for that

**Comment by hsl-petrhaj** [comment]
Thanks for letting me know, it is merged now. I will check the policies later in more detail.

**Pull request merged**
