### PR TITLE
Update VS Code instructions

### PR DESCRIPTION
**Pull request by zptro**
Solve issue with testing in updated version of VS Code

### CODE REVIEW

**Comment by hsl-petrhaj** [comment]
@zptro I did not understand from the instructions, if this also works in Python 3.7. Which Python version have you used?

**Comment by zptro** [comment]
> @zptro I did not understand from the instructions, if this also works in Python 3.7. Which Python version have you used?

Python 3.7 is what I use and what did no longer work after my VS Code extensions were updated. Reverting these updates fixed the issue.

**Comment by hsl-petrhaj** [comment]
Ok, if it works that way, I will accept it now. For me pytest kept working somehow though.

**Review by hsl-petrhaj — APPROVED** [review]

**Comment by zptro** [comment]
> Ok, if it works that way, I will accept it now. For me pytest kept working somehow though.

Oh, can you see the tests in the Testing explorer in VS Code even if you have Python extension version 2024.0.0 or above?

**Comment by hsl-petrhaj** [comment]
I have the following:
Python 3.7
Test Explorer UI v2.21.1
Python Debugger 2024.2.0

Seems to work fine except for some logging error.

**Comment by zptro** [comment]
> I have the following: Python 3.7 Test Explorer UI v2.21.1 Python Debugger 2024.2.0
> 
> Seems to work fine except for some logging error.

I see. I haven't been using Test Explorer UI lately, as it is described as deprecated, and Python extension's test view has worked just as well. But I guess that the benefit of being deprecated is that it still works well with Python 3.7. :)

**Comment by zptro** [comment]
@hsl-petrhaj Could you look at this so we can close it?

**Comment by hsl-petrhaj** [comment]
Yes, I can check this.

**Review by hsl-petrhaj — APPROVED** [review]
Seems like I was running with a slightly older version before, now I bumped into the same issue and your fix indeed works.

**Review by samakinen — APPROVED** [review]

**Pull request merged**
