### PR TITLE
Pikaratikka is added in the mode checks

### PR DESCRIPTION
**Pull request by hsl-petrhaj**
Pikaratikka (light rail) was missing in the network checks

### CODE REVIEW

**Comment by hsl-petrhaj** [comment]
@zptro or @johpiip please review

**Comment by johpiip** [comment]
@hsl-petrhaj, you need to mark us as reviewers in the right tab. That gives us an email notice and we can start reviewing. 😊
kuva

**Comment by hsl-petrhaj** [comment]
@johpiip I was wondering why is this not getting approved :D

**Review by zptro — APPROVED** [review]
Looks good to me!

**Pull request merged**
