### PR TITLE
modified generation code for script parameters.py

### PR DESCRIPTION
**Pull request by TimoElolahde**
modified generation code (variables and values) for script parameters.py

### CODE REVIEW

**Comment by zptro** [comment]
In my opinion, best practice would be to add empty "zone" entries to all tour groups that do not have any zone variables. In this way the program does not just ignore all variables if "zone" is spelt wrong.

**Comment by TimoElolahde** [comment]
If there are no individual dummys in the sub model (e.g. util3), should there be an empty individual_dummy entry as well?

**Comment by zptro** [comment]
> 
> 
> If there are no individual dummys in the sub model (e.g. util3), should there be an empty individual_dummy entry as well?

Yes.

**Comment by zptro** [comment]
Looks very good! Will merge this.

**Pull request merged**
