### PR TITLE
Fix node number validation

### PR DESCRIPTION
**Pull request by zptro**
The previous method could not handle modes that are allowed in several node number intervals. The new method checks all modes, not only transit modes.

### CODE REVIEW

**Review by johpiip — APPROVED** [review]
Interesting approach! Are there tests written on these validation procedures?

**Comment by zptro** [comment]
> Interesting approach! Are there tests written on these validation procedures?

Yes, the network validation is tested here: https://github.com/HSLdevcom/helmet-model-system/blob/39b57ecbbd541ab993a6e5ff07dd08f66d6c5390/Scripts/tests/unit/test_assignment.py#L31-L33

Maybe it should be separated into into an own test for clarity.

**Comment by johpiip** [comment]
Ah, okay, thanks! I just thought that if a new validation procedure was added here, there could also be a new test case to test it.

**Comment by zptro** [comment]
> Ah, okay, thanks! I just thought that if a new validation procedure was added here, there could also be a new test case to test it.

Yes, you are right. Overall, tests should be improved and actually test different cases.

**Pull request merged**
