### PR TITLE
Align columns better with values padded up to 12 digits

### PR DESCRIPTION
**Pull request by zptro**
- Align columns better with values padded up to 12 digits
- Restrict number of significant digits to 7, larger numbers as exponents

### CODE REVIEW

**Review by johpiip — COMMENTED** [review]
When decimal numbers are rounded to 7 significant digits, trailing zeros are dropped. This can be verified in `workforce_accessibility_per_area.txt` where `helsinki_cbd	4571.64987`becomes `espoo_vant_kau	    3993.185` (7 significant digits = 7 digits) but `helsinki_cbd	4571.64987` becomes `  helsinki_cbd	     4571.65` (7 significant digits = 6 digits because last one is rounded to zero). Is this intentional? Both ways are fine by me.

**Comment by zptro** [comment]
Should ask users if they want this change or not.

**Comment by johpiip** [comment]
@zptro My comment in Teams was about whitespaces but [my comment in this PR](https://github.com/HSLdevcom/helmet-model-system/pull/283#pullrequestreview-631144186) was about significant digits. I like the idea of explicitly rounding to seven significant digits but I commented on trailing zeros. :)

**Comment by zptro** [comment]
> @zptro My comment in Teams was about whitespaces but [my comment in this PR](https://github.com/HSLdevcom/helmet-model-system/pull/283#pullrequestreview-631144186) was about significant digits. I like the idea of explicitly rounding to seven significant digits but I commented on trailing zeros. :)

Yes, maybe I could do a separate PR, changing `%1.5f` into `%.7g`.

**Pull request closed without merging**
